import './side-navigation';
import './_3_dashboard-navigation';
import Menu from './menu';
import MenuBar from './menu';
import SubNavigation from './sub-navigation';
import Tab from './tabs';
import FlexiHeader from './header';
import Accordion from './accordion';
//export default Tab;
export { Menu, MenuBar, SubNavigation, Tab, FlexiHeader, Accordion };
